import { Link } from "wouter";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  ArrowLeft, Scale, Shield, FileText, AlertTriangle, Landmark,
  HandshakeIcon, CreditCard, Clock, Key, Globe, Gavel,
  ScrollText, Building2, RefreshCw, Ban
} from "lucide-react";
import logoPath from "@assets/hopsvoir_principal_logo_1769965389226.png";
import { AppFooter } from "@/components/app-footer";

export default function FranchiseCharter() {
  const lastUpdated = "March 5, 2026";

  const sections = [
    {
      icon: ScrollText,
      title: "1. Preamble & Recitals",
      content: [
        "This Franchise Agreement/Charter (\"Agreement\") is entered into between HOPS-TECH INNOVATION (Pty) Ltd (\"Franchisor\", \"HOPSVOIR\") and the subscribing Tenant (\"Franchisee\").",
        "WHEREAS the Franchisor owns and operates the HOPSVOIR platform, a proprietary SaaS solution for car wash and parking management;",
        "WHEREAS the Franchisor has developed proprietary systems, processes, branding, and technology constituting the HOPSVOIR business model;",
        "WHEREAS the Franchisee wishes to obtain a licence to operate under the HOPSVOIR brand and utilize the Platform;",
        "NOW THEREFORE, in consideration of the mutual covenants and agreements set forth herein, and for other good and valuable consideration, the parties agree as follows."
      ]
    },
    {
      icon: FileText,
      title: "2. Definitions",
      content: [
        "\"Agreement\" means this Franchise Agreement/Charter including all schedules, annexures, and amendments.",
        "\"Effective Date\" means the date on which the Franchisee completes registration and the Franchisor activates the Tenant account.",
        "\"Territory\" means the geographical area within which the Franchisee is authorized to operate, as specified in Schedule A.",
        "\"Initial Term\" means the initial period of this Agreement as specified in the subscription plan, commencing on the Effective Date.",
        "\"Renewal Term\" means each successive period following the Initial Term, subject to renewal conditions herein.",
        "\"System\" means the HOPSVOIR proprietary business system, including the Platform, operational methods, branding, training materials, and all related intellectual property.",
        "\"Marks\" means the HOPSVOIR trademarks, service marks, trade names, logos, and other commercial symbols owned by the Franchisor.",
        "\"Gross Revenue\" means all revenue generated by the Franchisee through or in connection with the operation of the franchised business."
      ]
    },
    {
      icon: Key,
      title: "3. Grant of Franchise",
      content: [
        "The Franchisor hereby grants to the Franchisee a non-exclusive, non-transferable, revocable licence to operate a car wash and/or parking management business using the System and the Marks.",
        "The franchise is granted for the Territory specified in Schedule A. The Franchisee shall not operate, advertise, or solicit business outside the designated Territory without prior written consent.",
        "This grant does not confer any exclusive territorial rights unless expressly stated in Schedule A.",
        "The Franchisee acknowledges that the Franchisor retains the right to operate company-owned locations, grant additional franchises, and develop the System within and outside the Territory.",
        "The licence granted herein is personal to the Franchisee and may not be assigned, transferred, sub-licensed, or encumbered without the prior written consent of the Franchisor."
      ]
    },
    {
      icon: CreditCard,
      title: "4. Fees & Financial Obligations",
      content: [
        "Initial Franchise Fee: A one-time, non-refundable fee as specified in the selected subscription plan, payable upon execution of this Agreement.",
        "Monthly Subscription Fee: Recurring monthly fee based on the active plan — Free (R0), Basic (R499/month), Pro (R1,499/month), Enterprise (Custom pricing).",
        "Royalty Fee: A percentage of Gross Revenue as specified in Schedule B, payable monthly within 15 days of month-end.",
        "Technology Fee: Included in the Monthly Subscription Fee, covering Platform access, updates, maintenance, and technical support.",
        "Marketing Contribution: The Franchisee shall contribute to the national marketing fund as specified in Schedule B (if applicable to the plan tier).",
        "Late Payment: Payments not received within 15 days of the due date will incur a late fee of 2% per month on the outstanding balance.",
        "The Franchisor reserves the right to suspend Platform access for accounts with payments overdue by more than 30 days.",
        "All fees are exclusive of VAT and applicable taxes, which shall be borne by the Franchisee."
      ]
    },
    {
      icon: HandshakeIcon,
      title: "5. Franchisor Obligations",
      content: [
        "Provide access to the HOPSVOIR Platform in accordance with the selected subscription plan and its features.",
        "Provide initial training and onboarding for the Franchisee and their Authorized Personnel.",
        "Provide ongoing technical support during business hours (Monday to Friday, 08:00–17:00 SAST), with extended support for Pro and Enterprise plans.",
        "Maintain, update, and improve the Platform, including bug fixes, security patches, and feature enhancements.",
        "Provide brand guidelines, marketing templates, and promotional materials.",
        "Conduct periodic performance reviews and provide recommendations for business improvement.",
        "Protect the integrity of the HOPSVOIR brand and enforce quality standards across the franchise network.",
        "Process and facilitate billing, subscription management, and payment collection through the Platform."
      ]
    },
    {
      icon: Building2,
      title: "6. Franchisee Obligations",
      content: [
        "Operate the franchised business in strict compliance with the System, this Agreement, and the Tenant Code of Conduct.",
        "Maintain all required business licences, permits, and insurance policies as required by applicable law.",
        "Ensure all staff complete mandatory training before performing services or accessing the Platform.",
        "Maintain facilities, equipment, and vehicles to the standards prescribed by the Franchisor.",
        "Use only the Platform for recording transactions, managing bookings, tracking services, and reporting.",
        "Permit the Franchisor to conduct inspections and audits at any time with reasonable notice.",
        "Promptly report any complaints, incidents, legal proceedings, or regulatory actions to the Franchisor.",
        "Pay all fees, royalties, and contributions punctually as specified in this Agreement.",
        "Not engage in any activity that could damage the reputation or goodwill of the HOPSVOIR brand.",
        "Maintain adequate insurance including public liability, professional indemnity, and property insurance."
      ]
    },
    {
      icon: Shield,
      title: "7. Intellectual Property & Confidentiality",
      content: [
        "All intellectual property rights in the System, Platform, Marks, and related materials are and shall remain the exclusive property of the Franchisor.",
        "The Franchisee is granted a limited, revocable licence to use the Marks solely in connection with the operation of the franchised business and in accordance with the brand guidelines.",
        "The Franchisee shall not register, or attempt to register, any trademark, domain name, or social media handle that is confusingly similar to the Marks.",
        "All Confidential Information disclosed by the Franchisor must be kept strictly confidential and used only for the purpose of operating the franchised business.",
        "The confidentiality obligation survives termination of this Agreement for a period of 5 (five) years.",
        "The Franchisee shall implement reasonable security measures to protect Confidential Information from unauthorized access, disclosure, or use.",
        "Any breach of confidentiality entitles the Franchisor to seek injunctive relief and damages without the necessity of proving actual loss."
      ]
    },
    {
      icon: Globe,
      title: "8. Data Protection & Privacy",
      content: [
        "Both parties shall comply with all applicable data protection laws including POPIA and GDPR.",
        "The Franchisor acts as the data controller for Platform data. The Franchisee acts as a data processor for customer data collected through the Platform.",
        "The Franchisee shall process personal data only in accordance with the Franchisor's instructions and this Agreement.",
        "The Franchisee must implement appropriate technical and organizational measures to ensure the security of personal data.",
        "In the event of a data breach, the Franchisee must notify the Franchisor within 24 hours of becoming aware of the breach.",
        "The Franchisee shall assist the Franchisor in responding to data subject access requests within the timeframes prescribed by law.",
        "Upon termination, the Franchisee shall return or securely destroy all personal data in its possession within 30 days."
      ]
    }
  ];

  const additionalSections = [
    {
      icon: Clock,
      title: "9. Term, Renewal & Termination",
      items: [
        "The Initial Term commences on the Effective Date and continues for the period specified in the subscription plan (monthly for Free/Basic, annual for Pro/Enterprise unless otherwise agreed).",
        "This Agreement shall automatically renew for successive Renewal Terms of equal duration unless either party provides written notice of non-renewal at least 30 days before the end of the current term.",
        "The Franchisor may terminate this Agreement immediately upon written notice if the Franchisee: commits a Critical Violation as defined in the Tenant Code of Conduct; becomes insolvent, enters liquidation, or is placed under business rescue; fails to cure a material breach within 30 days of written notice; is convicted of a criminal offence involving dishonesty, fraud, or moral turpitude.",
        "The Franchisee may terminate this Agreement by providing 60 days' written notice, subject to payment of all outstanding fees and fulfilment of all remaining obligations.",
        "Upon termination: the Franchisee must immediately cease using the Marks, System, and all HOPSVOIR materials; return or destroy all Confidential Information; settle all outstanding financial obligations within 30 days; the Franchisor will provide data export for 30 days post-termination.",
        "Post-termination, the Franchisee agrees to a non-compete period of 12 months within the Territory, during which they shall not operate a competing business using substantially similar methods or systems."
      ]
    },
    {
      icon: AlertTriangle,
      title: "10. Limitation of Liability & Indemnification",
      items: [
        "The Platform is provided \"as is\" without warranties of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, or non-infringement.",
        "The Franchisor's total aggregate liability under this Agreement shall not exceed the total fees paid by the Franchisee in the 12 months preceding the claim.",
        "The Franchisor shall not be liable for any indirect, incidental, consequential, special, or punitive damages, including loss of profits, revenue, data, or business opportunities.",
        "The Franchisee shall indemnify and hold harmless the Franchisor from any claims, damages, losses, or expenses arising from: the Franchisee's operation of the business; any breach of this Agreement; any violation of applicable law; any act or omission of the Franchisee's employees or agents.",
        "Neither party shall be liable for failure to perform obligations due to force majeure events including natural disasters, war, pandemic, government action, or disruption of telecommunications infrastructure."
      ]
    },
    {
      icon: Gavel,
      title: "11. Dispute Resolution",
      items: [
        "The parties shall first attempt to resolve any dispute through good-faith negotiation within 30 days of written notice of the dispute.",
        "If negotiation fails, the dispute shall be referred to mediation conducted by a mutually agreed mediator. The costs of mediation shall be shared equally.",
        "If mediation fails within 60 days, the dispute shall be referred to binding arbitration in accordance with the Arbitration Act applicable in the jurisdiction of the Franchisor.",
        "The arbitration shall be conducted in English, and the seat of arbitration shall be Johannesburg, South Africa.",
        "Notwithstanding the above, either party may seek urgent interim relief or injunctive relief from a court of competent jurisdiction.",
        "This Agreement shall be governed by and construed in accordance with the laws of the Republic of South Africa."
      ]
    },
    {
      icon: RefreshCw,
      title: "12. Transfer & Assignment",
      items: [
        "The Franchisee may not assign, transfer, or encumber this Agreement or any rights hereunder without the prior written consent of the Franchisor.",
        "The Franchisor may withhold consent to transfer at its sole discretion, or may grant consent subject to conditions including: the proposed transferee meeting the Franchisor's qualification standards; payment of a transfer fee; the proposed transferee completing required training; execution of a new Franchise Agreement.",
        "In the event of the death or permanent incapacity of the Franchisee (if a natural person), the Franchisee's estate or legal representative shall have 90 days to either transfer the franchise to a qualified successor or wind down operations.",
        "The Franchisor reserves the right of first refusal on any proposed transfer."
      ]
    },
    {
      icon: Ban,
      title: "13. Non-Compete & Non-Solicitation",
      items: [
        "During the term of this Agreement and for 12 months following termination, the Franchisee shall not directly or indirectly own, manage, operate, or have any financial interest in a business that competes with HOPSVOIR within the Territory.",
        "The Franchisee shall not solicit or recruit any employees of the Franchisor or other Franchisees during the term and for 12 months following termination.",
        "The Franchisee shall not solicit or divert customers of the franchised business to a competing business during the term and for 12 months following termination.",
        "The parties acknowledge that these restrictions are reasonable and necessary to protect the Franchisor's legitimate business interests."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="sticky top-0 z-50 backdrop-blur-md bg-background/80 border-b border-border">
        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center gap-4">
          <Link href="/">
            <Button variant="ghost" size="icon" data-testid="button-back">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <img src={logoPath} alt="HOPSVOIR" className="h-8" />
        </div>
      </header>

      <main className="flex-1 max-w-4xl mx-auto px-4 py-12 w-full">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <Badge variant="secondary" className="mb-4">
            <Landmark className="w-3 h-3 mr-1" />
            Legal
          </Badge>
          <h1 className="text-3xl md:text-4xl font-bold mb-3">Franchise Agreement & Charter</h1>
          <p className="text-lg text-muted-foreground mb-1">Official Franchise Agreement</p>
          <p className="text-sm text-muted-foreground">
            Last updated: {lastUpdated} · Document Version 1.0
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-8"
        >
          <Card className="border-primary/20">
            <CardContent className="pt-6">
              <p className="text-muted-foreground leading-relaxed mb-3">
                <strong>Between:</strong> HOPS-TECH INNOVATION (Pty) Ltd ("Franchisor") and the subscribing Tenant ("Franchisee")
              </p>
              <p className="text-muted-foreground leading-relaxed">
                This Agreement sets forth the terms and conditions under which the Franchisee is authorized to operate a car wash and/or parking management business using the HOPSVOIR proprietary system, brand, and technology platform. This Agreement is legally binding upon execution and governs the entire franchise relationship.
              </p>
            </CardContent>
          </Card>
        </motion.div>

        <div className="space-y-6">
          {sections.map((section, index) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.15 + index * 0.05 }}
            >
              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-start gap-4 mb-4">
                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                      <section.icon className="h-5 w-5 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h2 className="text-xl font-semibold mb-3">{section.title}</h2>
                      <ul className="space-y-2">
                        {section.content.map((item, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                            <span className="text-primary mt-1">•</span>
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}

          {additionalSections.map((section, index) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.55 + index * 0.05 }}
            >
              <Card>
                <CardContent className="pt-6">
                  <div className="flex items-start gap-4 mb-4">
                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                      <section.icon className="h-5 w-5 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h2 className="text-xl font-semibold mb-3">{section.title}</h2>
                      <ul className="space-y-2">
                        {section.items.map((item, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                            <span className="text-primary mt-1">•</span>
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.85 }}
          className="mt-6 space-y-6"
        >
          <Card>
            <CardContent className="pt-6">
              <h2 className="text-lg font-semibold mb-3">14. General Provisions</h2>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong>Entire Agreement:</strong> This Agreement, together with the Tenant Code of Conduct and all schedules, constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, and agreements.</span></li>
                <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong>Severability:</strong> If any provision of this Agreement is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.</span></li>
                <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong>Waiver:</strong> No failure or delay by either party to exercise any right shall constitute a waiver of that right.</span></li>
                <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong>Amendments:</strong> This Agreement may only be amended in writing signed by both parties, except for updates to the Platform features, subscription plan limits, and pricing which the Franchisor may update with 30 days' notice.</span></li>
                <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong>Notices:</strong> All formal notices must be in writing and delivered via registered mail, email to the registered email address, or through the Platform's notification system.</span></li>
                <li className="flex items-start gap-2"><span className="text-primary mt-1">•</span><span><strong>Independent Contractor:</strong> The Franchisee is an independent contractor and not an employee, partner, or agent of the Franchisor. Nothing in this Agreement creates a partnership, joint venture, or employment relationship.</span></li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-muted/50">
            <CardContent className="pt-6">
              <h2 className="text-lg font-semibold mb-3">15. Execution</h2>
              <p className="text-sm text-muted-foreground mb-4">
                By registering for and activating a HOPSVOIR Tenant account, the Franchisee acknowledges that they have read, understood, and agree to be bound by this Franchise Agreement/Charter in its entirety. This digital acceptance constitutes a legally binding agreement equivalent to a handwritten signature.
              </p>
              <div className="border-t pt-4 mt-4 space-y-3">
                <div>
                  <p className="text-sm font-semibold">FRANCHISOR:</p>
                  <p className="text-sm text-muted-foreground">HOPS-TECH INNOVATION (Pty) Ltd</p>
                  <p className="text-xs text-muted-foreground">Registration No: [Company Registration Number]</p>
                </div>
                <div>
                  <p className="text-sm font-semibold">FRANCHISEE:</p>
                  <p className="text-sm text-muted-foreground">As per registered Tenant account details</p>
                </div>
                <div className="border-t pt-3 mt-3">
                  <p className="text-xs text-muted-foreground">
                    For legal enquiries: <a href="mailto:legal@hopstecinnovation.com" className="text-primary hover:underline">legal@hopstecinnovation.com</a>
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </main>

      <AppFooter />
    </div>
  );
}

